### ISSUE TITLE
java.lang.IllegalStateException

### ISSUE THREAD

**Issue by cooliean** [traex/RippleEffect#104]
java.lang.IllegalStateException
Underflow in restore - more restores than saves

Android 6.0,level 23

android.graphics.Canvas.native_restore(Native Method)
android.graphics.Canvas.restore(Canvas.java:540)
- com.andexert.library.RippleView.draw(RippleView.java:166)

android.view.View.updateDisplayListIfDirty(View.java:15284)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3603)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3583)

**Comment by patrickpissurno** [comment]
Please try this fixed version as alternative (you can use any targetSdkVersion): https://github.com/patrickpissurno/RippleEffect/
