### ISSUE TITLE
Ripple event listener

### ISSUE THREAD

**Issue by dmacan23** [traex/RippleEffect#27]
Hi, first of all, I would like to say thanks for this lib (it is my favourite amongst other ripple libraries). 

However, I was wondering; is there any chance that you could add ripple event listeners (e.g. onRippleAnimationComplete), or custom onClick listeners, so that we wouldn't need to use delayed execution to display ripple first and then execute our code?
Also, will there be any methods like "rippleStop" to stop ripple display?

**Comment by angelen10** [comment]
@csbhalerao It does work for me.Has it something wrong for my code?
@Override
    public void draw(Canvas canvas) {
        super.draw(canvas);
        if (animationRunning) {
            if (DURATION <= timer * FRAME_RATE) {
                animationRunning = false;
                childView.performClick();
                timer = 0;
                durationEmpty = -1;
                timerEmpty = 0;
                canvas.restore();
                invalidate();
                return;
            } else {
                canvasHandler.postDelayed(runnable, FRAME_RATE);
            }

I have added childView.performClick(); when animationRunning = false at draw function,But it does not take effect.

**Comment by frapontillo** [comment]
:+1: this is a much needed feature.

**Comment by traex** [comment]
PR #44 solved this issue, see release 1.3 in tomorrow :)

**Comment by frapontillo** [comment]
@traex awesome!
