### ISSUE TITLE
Onitemclicklistener not working on listview with this library

### ISSUE THREAD

**Issue by manpreetsinghsodhi** [traex/RippleEffect#32]
I used the same code as you used . Only difference is i used listview in place of recyclerview.
I applied ripple widget to the list item that i inflated. I kept that ripple widget com.andexert.library.RippleView as parent(same as you did) in row_view.xml.  By doing this ripples are applied well but on click listener of list view stopped working. Please help me how to resolve this

**Comment by FatihPolat** [comment]
+1

**Comment by RyanDam** [comment]
+1

**Comment by synic** [comment]
+1

**Comment by traex** [comment]
Hi everyone,
I'm working on it. I will release a new release tomorrow :smile:. I'm sorry for the delay

**Comment by MinsungHuh** [comment]
Plz updated version.. this issue isn't fixed yet.

**Comment by traex** [comment]
I've just released a fix for this issue. It's v1.2.4. It will be available in the night on maven repositories. You need to use the RippleView as root element in your row if you want to use it with a ListView

**Comment by traex** [comment]
Is this update fix your issue ? @MinsungHuh  @manpreetsinghsodhi

**Comment by Hypertje** [comment]
The fix worked for the clickListener. However, in the same activity, my onFling() stopped working. I don't know if this is related to the effect. I will check and test tonight to see what causes it. I will keep you informed.

**Comment by Hypertje** [comment]
It isn't related to the effect, so thank you very much!

**Comment by clopeziiia** [comment]
Thank you. You should update readme with the new version!

**Comment by sheko7** [comment]
Some solution for this issue?

**Comment by clopezuab** [comment]
As said before, use 1.2.4 instead of 1.2.3:

dependencies {
    compile 'com.github.traex.rippleeffect:library:1.2.4'
}

**Comment by sheko7** [comment]
Thanks, now it's worked, you could upgrade the readme (says compile 'com.github.traex.rippleeffect:library:1.2.3')

**Comment by clopezuab** [comment]
Haha, I would say the same! But I'm not the developer.

**Comment by suryasunger75** [comment]
Hi, I am trying using com.github.traex.rippleeffect:library:1.3 along with 
com.android.support:appcompat-v7:24.2.0' and compile 'com.android.support:design:24.2.0'

I am using it on Custom Gridview but the  setOnItemClickListener stop working. Pls help
