### ISSUE TITLE
Error when importing using Android-Studio (using Git)

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [traex/RippleEffect#33]
I've tried to import the project using Android-Studio, and I got this during the import process, which means it fails:

![untitled20141227223953](https://cloud.githubusercontent.com/assets/5357526/5562283/4e4bae16-8e19-11e4-9950-5110c3910879.png)

Any way to solve this?

**Comment by traex** [comment]
Hi,
You just have to comment this line in the build.gradle of the library module : 
`apply from: 'https://raw.github.com/chrisbanes/gradle-mvn-push/master/gradle-mvn-push.gradle'`

**Comment by AndroidDeveloperLB** [comment]
I don't understand. This dialog was shown when importing. Not after that... How could I edit anything if it wasn't imported correctly?
You mean I should open the file outside of Android-Studio, and comment this line? What is this line, and why does it cause issues?

**Comment by traex** [comment]
Checkout the v1.2.4 I added a fix for this then import it as a non AndroidStudio  project and it will work fine :D

**Comment by AndroidDeveloperLB** [comment]
Thank you. Seems to work fine now.
However, I see that the ripple effect doesn't use the native one in case it's Lollipop, and it's a bit slow.
It does look nice though.
