### ISSUE TITLE
Not working with Recyler view OnClickListener

### ISSUE THREAD

**Issue by Ashok-Varma** [traex/RippleEffect#37]
I had a recyler view in which i had item.setOnClickListener for each element and the OnClickListener is not working with this library

**Comment by traex** [comment]
Can you take a look at the sample ?

**Comment by ryanamaral** [comment]
@Ashok-Varma, you probably didn't set the click listener on the RippleView.
```
final RippleView rippleView = (RippleView) findViewById(R.id.rippleView);
rippleView.setOnClickListener(new View.OnClickListener() {
    @Override
    public void onClick(View v) {
        //TODO: onRippleViewClick
    }
});
```
@traex, I think would be better to add this kind of information to the README.
Btw, great job with your library! ;)

**Comment by traex** [comment]
Thanks @ryanamaral, it's updated ;)
