### ISSUE TITLE
delete ic_launcher.png

### ISSUE THREAD

**Issue by hangox** [traex/RippleEffect#56]
can not build succeed in andoid gradle tool 1.2.2

**Comment by voldcs** [comment]
Works fine with 1.2.2 just change  buildToolsVersion to "21.1.2"

**Comment by hangox** [comment]
but it not good for a library ，it is useless

**Comment by voldcs** [comment]
Can you please be more specific:  what is not good particularly?

**Comment by hangox** [comment]
ic_launcher.png is useless for a library，it also can make our apk bigger .

voldcs <notifications@github.com>于2015年5月8日周五 下午9:07写道：

**Comment by voldcs** [comment]
you initial statement was about build fail on gradle tool 1.2.2, I pointed you how to make it successful. I wasn't talking about ic_launcher.png

**Comment by hangox** [comment]
I got it . I think you are author,But I wrong.

voldcs <notifications@github.com>于2015年5月9日周六 下午6:28写道：

**Comment by NeoLSN** [comment]
I got same problem, too.

**Comment by traex** [comment]
It's fixed :)
