### ISSUE TITLE
app:rv_rippleDuration is not working

### ISSUE THREAD

**Issue by ashishkudale** [traex/RippleEffect#66]
this two attributes are not working

app:rv_rippleDuration="1200"
app:rv_color="#d3d3d3"

ripple effect should complete first then action should be called. But here action is get called as soon as button is clicked. User cannot experience animation.

**Comment by traex** [comment]
Hi,

For the `rv_color` it works perfectly
For the `rv_rippleDuration` it's the normal behavior. You're talking about another feature already added to my todo list.

Thanks for your time ;)
