### ISSUE TITLE
Underflow in restore - more restores than saves : on Android M (6.0)

### ISSUE THREAD

**Issue by arsalancode** [traex/RippleEffect#76]
09-09 08:42:48.592 13857 13857 E AndroidRuntime: java.lang.IllegalStateException: Underflow in restore - more restores than saves
09-09 08:42:48.592 13857 13857 E AndroidRuntime: 	at android.graphics.Canvas.native_restore(Native Method)
09-09 08:42:48.592 13857 13857 E AndroidRuntime: 	at android.graphics.Canvas.restore(Canvas.java:540)
09-09 08:42:48.592 13857 13857 E AndroidRuntime: 	at com.andexert.library.RippleView.draw(RippleView.java:166)
09-09 08:42:48.592 13857 13857 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:15174)
09-09 08:42:48.592 13857 13857 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
09-09 08:42:48.592 13857 13857 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
09-09 08:42:48.592 13857 13857 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:15134)
09-09 08:42:48.592 13857 13857 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
09-09 08:42:48.592 13857 13857 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
09-09 08:42:48.592 13857 13857 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:15134)
09-09 08:42:48.592 13857 13857 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
09-09 08:42:48.592 13857 13857 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
09-09 08:42:48.592 13857 13857 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:15134)
09-09 08:42:48.592 13857 13857 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
09-09 08:42:48.592 13857 13857 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
09-09 08:42:48.592 13857 13857 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:15134)
09-09 08:42:48.592 13857 13857 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
09-09 08:42:48.592 13857 13857 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
09-09 08:42:48.592 13857 13857 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:15134)
09-09 08:42:48.592 13857 13857 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
09-09 08:42:48.592 13857 13857 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
09-09 08:42:48.592 13857 13857 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:15134)
09-09 08:42:48.592 13857 13857 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
09-09 08:42:48.592 13857 13857 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
09-09 08:42:48.592 13857 13857 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:15134)
09-09 08:42:48.592 13857 13857 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
09-09 08:42:48.592 13857 13857 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
09-09 08:42:48.592 13857 13857 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:15134)
09-09 08:42:48.592 13857 13857 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
09-09 08:42:48.592 13857 13857 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
09-09 08:42:48.592 13857 13857 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:15134)
09-09 08:42:48.592 13857 13857 E AndroidRuntime: 	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:281)
09-09 08:42:48.592 13857 13857 E AndroidRuntime: 	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:287)
09-09 08:42:48.592 13857 13857 E AndroidRuntime: 	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:322)
09-09 08:42:48.592 13857 13857 E AndroidRuntime: 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2615)
09-09 08:42:48.592 13857 13857 E AndroidRuntime: 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2434)
09-09 08:42:48.592 13857 13857 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2067)
09-09 08:42:48.592 13857 13857 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
09-09 08:42:48.592 13857 13857 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
09-09 08:42:48.592 13857 13857 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
09-09 08:42:48.592 13857 13857 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
09-09 08:42:48.592 13857 13857 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:606)
09-09 08:42:48.592 13857 13857 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
09-09 08:42:48.592 13857 13857 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
09-09 08:42:48.592 13857 13857 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
09-09 08:42:48.592 13857 13857 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
09-09 08:42:48.592 13857 13857 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
09-09 08:42:48.592 13857 13857 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-09 08:42:48.592 13857 13857 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
09-09 08:42:48.592 13857 13857 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by matthewrice345** [comment]
I get this error too.

**Comment by fleficher** [comment]
Same thing on Nexus 6 on Android 6.0 Build MPA44G.
Seems to be a Android bug, i've checked and there are as many restores as saves...

**Comment by esiek** [comment]
I get this error too.

**Comment by JolandaVerhoef** [comment]
This is still crashing in the Official release of Android 6.0 that Google is rolling out.

**Comment by varunrramani** [comment]
Even I'm getting the same error on Android One device running Android 6.0

**Comment by gilgil28** [comment]
same here...

**Comment by JolandaVerhoef** [comment]
I moved over to `com.balysv:material-ripple:1.0.2`, that library doesn't crash.

It seems to crash for us when we open another app from a button. Then when we return to the app, it tries to finish the ripple animation and crashes.

**Comment by varunrramani** [comment]
@JolandaVerhoef  check https://github.com/traex/RippleEffect/issues/74 comment by matthewrice345. He suggests modifying the source code.

**Comment by akbarsha03** [comment]
Same issue here... Gonna place a separate layout for 21+

**Comment by vipinshukla83** [comment]
I am also getting same error on Android 6.0

**Comment by akbarsha03** [comment]
@vipinshukla83 Place separate layout for 21+ let the Android M handle the ripple itself. Just use the proper ripple holder for layouts and views

**Comment by EliasGabrielsson** [comment]
I also have this problem, Android 6.0

**Comment by loveanao** [comment]
I also have this problem, Android 6.0

**Comment by dariav** [comment]
I've just created PR for this.
In case you don't want to wait for it and can use JitPack in your project you can get it by using
`compile 'com.github.Hitta:RippleEffect:82cf00e551'`

**Comment by rex3du** [comment]
@dariav  compile 'com.github.Hitta:RippleEffect:82cf00e551' is not working for me

**Comment by dariav** [comment]
@rex3du Have you tried adding JitPack repository to your build file
```
repositories {
			...
			maven { url "https://jitpack.io" }
		}
```

**Comment by rex3du** [comment]
@dariav  Thanks.

**Comment by ghost** [comment]
Hi, i am using this library in my project and I can see you made the changes to fix the error with marshmallow. However I don't know how to apply/get/make those fixes in my project.

**Comment by GirishBhalerao** [comment]
This has very simple solution. Just downgrade your - targetSdkVersion to 22
It works for all versions.

**Comment by GirishBhalerao** [comment]
There are two solutions for this Problem. 
1) As I mentioned before - "Just downgrade your - targetSdkVersion to 22
It works for all versions" - This works fine if you have not launched your app with targetSdkVersion 23 yet. 
2) If you already have launched your app with targetSdkVersion 23 then, 
instead of adding  compile 'com.github.traex.rippleeffect:library:1.3' in dependancies, 
Download the project by clicking on link - https://codeload.github.com/traex/RippleEffect/zip/master
Get library from that and use that in your app. It works great...!!! :)

**Comment by dushan135** [comment]
@GirishBhalerao  how to get the library and import it to my app??

**Comment by Gloomyer** [comment]
Me too, in Xiaomi  android 6.0.

**Comment by levi-mendes** [comment]
Me too Motorola Moto G Android 6.0.

**Comment by Jaftem** [comment]
Getting this on Android 7.0, Nexus 6p.

**Comment by AresCool** [comment]
I also have this problem, Android 6.0.How do you solve it ?

**Comment by foxcode7** [comment]
i also have this problem on Android 7.0, Nexus 6p.

**Comment by williamthegrey** [comment]
I Got this problem too on Android 7.0, Nexus 5X.

**Comment by XuanGao2023** [comment]
I Got this too.

**Comment by suyashbhagwat** [comment]
@GirishBhalerao  works well on Android 7.0 on Nexus 6 ..
Thanks..

**Comment by Sajini12** [comment]
Does this issue takes place only on button, or the error occurs on Cardview as well. I am using a cardview and not getting any crash.

**Comment by dingypgit** [comment]
call  canvas.save(); before every restore()

**Comment by franklinexpress** [comment]
Getting this too, android 6

**Comment by bravolover520** [comment]
android 自定义view报如下错误：  java.lang.IllegalStateException: Underflow in restore
原因：在自定义view里面调用了如下方法来保存画布的bitmap图像;
mCanvas.restore()
解决方法：改成：
mCanvas.save(); 
mCanvas.restore();
Okay！解决！

**Comment by dongshiliang** [comment]
upper version 22
call    mCanvas.save();          before every         mCanvas.restore();

**Comment by patrickpissurno** [comment]
Please try this fixed version as alternative (you can use any targetSdkVersion): https://github.com/patrickpissurno/RippleEffect/

**Comment by Rafiqgithub** [comment]
@patrickpissurno 
Thanks man its working now error free.

**Comment by ErickDaniel** [comment]
@bravolover520 work 4me

**Comment by chrissen0814** [comment]
l have the same problem and the version 1.3.1 is not working for me. Android 6.0.1

**Comment by shahilpb** [comment]
Same problem

**Comment by SuperBeagleDog** [comment]
I did as bravolover520 said (commented on 12 Jan 2017) ==   Called canvas.save(); Before canvas.restore();
Anyway, I can't change the source code. So that I copied the source and created a new one to fix this problem..

**Comment by eingurat504** [comment]
I fixed this issue using this version of RippleEffect https://github.com/patrickpissurno/RippleEffect/

**Comment by ski96277** [comment]
### **Use this. It's Work For me,**

`implementation` 'com.patrickpissurno:ripple-effect:1.3.1'`

### More details -------------
https://github.com/patrickpissurno/RippleEffect/
