### ISSUE TITLE
setRippleColor() 

### ISSUE THREAD

**Issue by jehad-suliman** [traex/RippleEffect#78]
I want to set a color that its not from res 
please fix It

**Comment by alfredmack** [comment]
This work
        ripple:rv_color="@color/primary"
or 
       ripple:rv_color="#ffffff"

remember to put
xmlns:ripple="http://schemas.android.com/apk/res-auto"

**Comment by HiroyukiTamura** [comment]
I want to _programmatically_ set a color that its not from res.
is it fixed?
