### ISSUE TITLE
Compile time error

### ISSUE THREAD

**Issue by impasse** [traex/RippleEffect#79]
Hi there,
Im trying to implement your lib to achive ripple effect in my app but getting compile time error for this android:layout_toLeftOf="@+id/more2". System is unable to find resource more2. Any idea?
Have a look-
https://www.dropbox.com/s/0sl1fx1o256oi6s/Screenshot%202015-09-16%2020.01.31.png?dl=0
Thx for this wonderful snippet.

**Comment by traex** [comment]
No idea please open an issue with more details and stacktrace. Thanks ;)
