### ISSUE TITLE
Crash on Android 6.0 in RippleView.draw()

### ISSUE THREAD

**Issue by emanzanoaxa** [traex/RippleEffect#81]
Today I've installed Android 6.0 (release) and ripple is crashing, here is the stacktrace:

E/AndroidRuntime: java.lang.IllegalStateException: Underflow in restore - more restores than saves
E/AndroidRuntime:     at android.graphics.Canvas.native_restore(Native Method)
E/AndroidRuntime:     at android.graphics.Canvas.restore(Canvas.java:540)
E/AndroidRuntime:     at com.andexert.library.RippleView.draw(RippleView.java:166)

**Comment by ChrisDolge** [comment]
Hi , 

i have the same problem.

**Comment by mistercz** [comment]
Same problem here!

**Comment by lbtrier** [comment]
Same for me, unfortunately

**Comment by emanzanoaxa** [comment]
I've sent a pull request fixing this issue, I hope the developer accepts it. If anyone is interested I have it in my fork https://github.com/emanzanoaxa/RippleEffect/tree/fix_marshmallow

**Comment by mistercz** [comment]
Thank you @emanzanoaxa! I

**Comment by paul321** [comment]
Guys, 

I don't think the author it's active anymore, can someone publish this project on maven / gradle with this fix

Thanks

**Comment by Frequencies** [comment]
+1

**Comment by rafalzawadzki** [comment]
@paul321, you can use the jitpack: https://jitpack.io/#emanzanoaxa/RippleEffect/v1.3

**Comment by paul321** [comment]
@rafalzawadzki Thank you, saved me a lot of trouble by including the source code in the project :)

**Comment by paul321** [comment]
It's still crashing using this repo

**Comment by paul-piro** [comment]
You need to use this one

```
compile 'com.github.emanzanoaxa:RippleEffect:52ea2a0ab6'
```

**Comment by susheel17** [comment]
@emanzanoaxa : Thank you for the fix! It works :)

**Comment by aminsepahan** [comment]
i couldn't use @emanzanoaxa's fix, and i dont know why!
it seems that it doesn't find it :/

**Comment by Seylox** [comment]
I have the same error and I'm probably gonna switch to a different library.

**Comment by EliasMazz** [comment]
+1

**Comment by nzackoya** [comment]
anything on this?

**Comment by jjesusn** [comment]
@emanzanoaxa Thanks!!!

**Comment by traex** [comment]
Please see #92. It will be released asap

**Comment by ysy950803** [comment]
Thanks very much! @emanzanoaxa

**Comment by GirishBhalerao** [comment]
This has very simple solution. Just downgrade your - targetSdkVersion to 22
It works for all versions.

**Comment by patrickpissurno** [comment]
Please try this fixed version as alternative (you can use any targetSdkVersion): https://github.com/patrickpissurno/RippleEffect/
