### ISSUE TITLE
java.lang.RuntimeException: Unable to instantiate activity ComponentInfo(com.activity.SplashScreen) . java.lang.Classnotfound

### ISSUE THREAD

**Issue by amanjain08** [traex/RippleEffect#88]
After adding this library in gradle the app starts crashing in Android 4.1 but it works better in Lollipop. 
SplashScreen.java is my main activity and I am unable to start my app.

**Comment by traex** [comment]
Can you open a new issue with more details and stacktrace please. Thanks ;)
