### ISSUE TITLE
How can I change Ripple color?

### ISSUE THREAD

**Issue by debugger22** [traex/RippleEffect#9]

**Comment by erdnuss13** [comment]
Sorry but that don't work for me.
Could you add a sample xml?

**Comment by itheark** [comment]
+1

**Comment by thomasbiddle** [comment]
@erdnuss13 @itheark 

You'll need `xmlns:app="http://schemas.android.com/apk/res-auto"`  as an xmlns in your file before you can use the `app` resource.
