### ISSUE TITLE
java.lang.IllegalStateException: Underflow in restore on Virtual Device

### ISSUE THREAD

**Issue by WaylanPunch** [traex/RippleEffect#90]
Is that normal if an **IllegalStateException** occurred when I ran it on the Genymotion Virtual Device ?
Because it is OK on real Android Device.
```sh
12-21 11:01:58.933 9458-9458/com.***.**** E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.***.****, PID: 9458
java.lang.IllegalStateException: Underflow in restore - more restores than saves
    at android.graphics.Canvas.native_restore(Native Method)
    at android.graphics.Canvas.restore(Canvas.java:540)
    at com.andexert.library.RippleView.draw(RippleView.java:166)
    at android.view.View.updateDisplayListIfDirty(View.java:15174)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
    at android.view.View.updateDisplayListIfDirty(View.java:15134)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
    at android.view.View.updateDisplayListIfDirty(View.java:15134)
    ......
```

**Comment by jeetdholakia** [comment]
Same problem here

**Comment by davroux** [comment]
I got it only for Android 6. Don't know how to remove this bug

**Comment by NSouth** [comment]
Same here. Happens every time on Marshmallow.

**Comment by jeetdholakia** [comment]
And happens on real devices , not just emulators/genymotion

**Comment by NSouth** [comment]
I ended up using the solution posted here. Just required adding two lines and commenting out the old compile statement in my gradle file.
https://github.com/traex/RippleEffect/issues/81#issuecomment-151215233

**Comment by jjhesk** [comment]
+1

**Comment by karthisammannan** [comment]
same problem...

**Comment by GirishBhalerao** [comment]
This has very simple solution. Just downgrade your - targetSdkVersion to 22
It works for all versions.

**Comment by GirishBhalerao** [comment]
There are two solutions for this Problem. 
1) As I mentioned before - "Just downgrade your - targetSdkVersion to 22
It works for all versions" - This works fine if you have not launched your app with targetSdkVersion 23 yet. 
2) If you already have launched your app with targetSdkVersion 23 then, 
instead of adding compile 'com.github.traex.rippleeffect:library:1.3' in dependancies, 
Download the project by clicking on link - https://codeload.github.com/traex/RippleEffect/zip/master
Get library from that and use that in your app. It works great...!!! :)

**Comment by saidurcse** [comment]
@GirishBhalerao Thanks for your good suggestion. :)

**Comment by patrickpissurno** [comment]
Please try this fixed version as alternative (you can use any targetSdkVersion): https://github.com/patrickpissurno/RippleEffect/

**Comment by ihewro** [comment]
@patrickpissurno  thank you for your work ! it help me !
