### ISSUE TITLE
How can I use it in a GridView?

### ISSUE THREAD

**Issue by Rachel030219** [traex/RippleEffect#91]
I want to use it in a GridView,but the events always start before the animation finishes.How can I fix it?(I am a Chinese so my English isn't so well...)

**Comment by snappy46** [comment]
Use the .setOnRippleCompleteListener() inside your Gridview onClick() listener and start your events on the onComplete(RippleView) versus your gridview onClick() listener.

**Comment by Rachel030219** [comment]
Thanks,snappy46.I got it.(・∀・)
